version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/redis:4.0.9

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "go.sum" }}
            - deps-{{ .Branch }}-
            - deps-
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 10s
      - run: go get github.com/onsi/ginkgo/ginkgo
      - run: go mod download
      - run: make coverage-ci
      - run: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - store_test_results:
          path: test-results
